'use client'

import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import React, { useEffect } from 'react';

const SPREADSHEET_ID = `1a_uPmMWO8Sww9fodrzP7oo_1b41OeejASuiHoRV6yOA`;
const SHEET_ID = `0`;
const CLIENT_EMAIL = `wedding-test@wedding-403513.iam.gserviceaccount.com`;
const PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCTDklZxmVHVz9+\nZUohXs2z9R4dtS3x6ixOhR/oITwCEiUZ9GpUv1nJtUWW3DNitj5xoyJU0Hwzm12Z\npMQIkNvr0Kw224VEmFZL2KDBq/wZZa5ciYI2oHrzzhi+TDINRm/7DWSGsovvp0Xi\nUte/NYfy58NM83NkWob0GFjsWekj1rDgLrys1CnR3BwrWyqMEuM0qLbD/m8SJYqW\njs/SjNFzHc7LrT5ASCxdmnmIU+7HEe5Xxdo2ZG04vw2bJoCDIdG43r051XXDNhvx\nSbIvLqfzgPfDGBMH2oSLYYIIwSwVKrJX5qoyxMgYO/UJKU8IYKNv7haTbyYuITZR\nPXGx3C5jAgMBAAECggEAFNa2cEFcAsMLXVbvLVFo5vJ6RQ1yqFBd3PaicdubzFNT\n7JylIMNI7vuAFAO6SGe465OJfulYYFvI5Mfje69DauRUMyXiebj4qaDWDvvXKqYt\nEjHuQN127uuqt/TGNvlfTv0z3J6ak+hpT8wbhJ4KWNKc61+oX3UwoJB+sWeAUTKZ\nMOUJFseRRwLn0xLp/CbffvjEPT/g1evFc9oR/bNvrmAEllRcz5tJ58BPkxfRIk1n\nt/GrVwIIujWgXPz/73Ras+BO0PsHlhmKEatpdcOiWqgyQgIlBQEE+QooJfVxb5/z\nQ94D0C1dKY5+hiS81sfeZgZSnLR7IL11DQlkx62yIQKBgQDJTuaZN9GeFxtspC9H\nZbl4z/W4mv8XkZljlLKWPl28IAgxr9H56QnbYD8IYtiQT+w/wu1L7s/7jEl7hN4e\nE+vgLquTKVEGHWo6IEARx+CoW7SyJ0ryfC9WoSJfP9vT69Aql5AvJNG8f7EAakT7\njBBCOMELrDQ+UQap9R3g/4nukwKBgQC7AhnNLrM2Az6i9XC3beKsarOCv9UGy8/X\nvVF3B0kKFUN0vlQVESRO3bTFwteRrb1KiXNiBLkyLw3vvMSRnSd+sitfLNTNHk8W\nvIQDcPMx1jDcRofFk1u8iW7t2yC8qcUvFBLmKxvVLxZE2JQ/wxUb8lNCHbJg+uLC\n+xu9GjrS8QKBgEYcZbHNQANIVvPShujd4+fQverKiLeDrSGCg2RSWkEQAuqTKpVY\ndWdjMPDRxE0WmNhoIk9E4EjixiDv2JAvLgKJHpaFWEPB8OJHoyjOLU9ViSxXBQJJ\nAA+y1Q7JZd18DqcW3E+fCjEVY+caG+ZkFLGLpKhVFGjzvVdqGDrppPdjAoGAKcrA\nZWBIYIu9FcHwHK4L+CgoUdH5E3m8yyPd7tHL+trhpldahxK7oHxfh8qRTlcbdGrf\nREp18McfQDJZY4lRaDj9BFoKfISHfDdI8VPupXaOmMuSUA8scyfriHBuEnuGO40q\n5BFCORQ6z8vu5Yj9UK+I97+XO6EVyClB+7K+7qECgYEAjxLVY6uOit5lxr5O5DjD\nXTQEpiJhbykjzjs+fokZr33G9EEtU0VC1JMvxARO9VrUvHgkrh2KLDDUyWOw0Mo9\n/XZmChfcmZT2Q1EB6Votk3ji7yyoXEy+RC+5LbKa20OKdl+ddtO0NwPspbK37fpa\nWKwr18yIpvk0OjJ0jEHpZDM=\n-----END PRIVATE KEY-----\n";


const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: CLIENT_EMAIL,
    key: PRIVATE_KEY,
    scopes: [
        'https://www.googleapis.com/auth/spreadsheets',
    ],
});

const doc = new GoogleSpreadsheet(SPREADSHEET_ID, serviceAccountAuth);
export default function Confirm() {
    useEffect( () => {
        const fetchData = async () => {
            // loads document properties and worksheets
            await doc.loadInfo();

            const sheet = doc.sheetsById[SHEET_ID];
            const rows = await sheet.getRows();
            for (let i = 0; i < rows.length; i++) {
                console.log(rows[i].get(`name`));
            }
        }

        fetchData()
    }, [])

    return (
        <div className="ww-section" id="confirm">
            <div className="col text-center container">
                <div id="fh5co-started" className="fh5co-section-gray">
                    <div className="overlay"></div>
                    <div className="container">
                        <div className="h1 text-center pb-3 ww-title">
                            {/*<div className="col-md-8 col-md-offset-2 text-center fh5co-heading">*/}
                                <p className="sub-title sub-title__wedding">Để chúng mình chuẩn bị chu đáo nhất</p>
                                <h2 className="main-font">{`Bạn vui lòng xác nhận tham dự`}</h2>
                                {/*<div onClick={onSelect(options.YES)}>*/}
                                <div>
                                    <input
                                        style={{marginRight: 8, marginTop: 16}}
                                        type="radio"
                                        id="ok"
                                        name="drone"
                                        // value={options.YES}
                                        // checked={selected === options.YES}
                                    />
                                    <label style={{fontSize: 18, fontWeight: 'normal'}} htmlFor="ok">
                                        {' '}
                                        Mình chắc chắn sẽ tham dự
                                    </label>
                                </div>
                                {/*<div onClick={onSelect(options.NO)}>*/}
                                <div>
                                    <input
                                        style={{marginRight: 8}}
                                        type="radio"
                                        id="no"
                                        name="drone"
                                        // value={options.NO}
                                        // checked={selected === options.NO}
                                    />
                                    <label style={{fontSize: 18, fontWeight: 'normal'}} htmlFor="no">
                                        {' '}
                                        Xin lỗi, mình không thể tham dự
                                    </label>
                                </div>
                            {/*</div>*/}
                        </div>
                        {/*<div className="row" css={styFlex}>*/}
                        {/*<div className="row">*/}
                        {/*    <div className="col-md-3">*/}
                        {/*        /!*<button onClick={submit} className="btn btn-default btn-block">*!/*/}
                        {/*        <button className="btn btn-default btn-block">*/}
                        {/*            /!*{submitting ? 'Đang gửi...' : 'Gửi'}*!/*/}
                        {/*        </button>*/}
                        {/*    </div>*/}
                        {/*</div>*/}
                    </div>
                </div>

            </div>

        </div>
    )
}